
# Sprint 5: Data Cleaning and Data Preprocessing

## Notebook 1: Data Preprocessing Fundamentals

### Objective
Understand the fundamentals of data preprocessing and learn how to
convert raw data into a clean, consistent, validated, and
machine-learning-ready dataset.

### Learning Outcomes
- Understand raw data versus clean data.
- Identify data-quality problems.
- Understand data consistency, completeness, accuracy, and validity.
- Understand data integrity and data leakage.
- Understand training, validation, and test datasets.
- Explain the complete preprocessing workflow.

In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Libraries imported successfully!")

Pandas version: 3.0.3
NumPy version: 2.4.6
Libraries imported successfully!


## 1. What is Data Preprocessing?

Data preprocessing is the process of converting raw data into a
clean, organized, consistent, and suitable format for analysis
and machine learning.

It involves identifying and handling missing values, duplicate
records, inconsistent values, incorrect data types, and outliers.
It can also include encoding categorical variables, scaling
numerical features, and selecting relevant features.

**Example:** Converting missing age values into appropriate
imputed values and standardizing category labels before training
a machine learning model.


## 2. Why Is Data Preprocessing Required?

Data preprocessing is important because raw data may contain
errors, missing values, duplicates, inconsistent formats, and
irrelevant information.

Poor-quality data can lead to unreliable analysis and inaccurate
machine learning predictions.

The main benefits are:
- Improved data quality.
- More consistent and reliable results.
- Better model training and evaluation.
- Reduced errors caused by incorrect data.
- Prevention of data leakage.
- More reproducible machine learning workflows.

In [2]:
raw_data = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Ravi", "Arun"],
    "Age": [25, np.nan, 25, 200],
    "City": ["Hyderabad", "hyderabad", "Hyderabad", "Chennai"],
    "Salary": [30000, 45000, 30000, -5000]
})

print("Raw Dataset:")
display(raw_data)

Raw Dataset:

    Name    Age       City  Salary
0   Ravi   25.0  Hyderabad   30000
1  Priya    NaN  hyderabad   45000
2   Ravi   25.0  Hyderabad   30000
3   Arun  200.0    Chennai   -5000

In [3]:
print("Dataset shape:", raw_data.shape)
print("\nMissing values:")
print(raw_data.isnull().sum())

print("\nDuplicate rows:", raw_data.duplicated().sum())

print("\nData types:")
print(raw_data.dtypes)

Dataset shape: (4, 4)

Missing values:
Name      0
Age       1
City      0
Salary    0
dtype: int64

Duplicate rows: 1

Data types:
Name          str
Age       float64
City          str
Salary      int64
dtype: object


## 3. Data Quality

Data quality describes how suitable data is for its intended use.

### Completeness
Checks whether required values are present.

### Accuracy
Checks whether values correctly represent real-world information.

### Validity
Checks whether values follow defined rules, formats, and ranges.

### Consistency
Checks whether the same information is represented uniformly
across records and systems.

### Uniqueness
Checks whether duplicate records exist when each record should
be unique.

### Integrity
Ensures that relationships and constraints between data records
remain correct.

These dimensions help determine which cleaning operations are
necessary before using data in machine learning.

In [4]:
print("City values before standardization:")
print(raw_data["City"].unique())

consistency_demo = raw_data.copy()
consistency_demo["City"] = (
    consistency_demo["City"]
    .str.strip()
    .str.title()
)

print("\nCity values after standardization:")
print(consistency_demo["City"].unique())

City values before standardization:
<ArrowStringArray>
['Hyderabad', 'hyderabad', 'Chennai']
Length: 3, dtype: str

City values after standardization:
<ArrowStringArray>
['Hyderabad', 'Chennai']
Length: 2, dtype: str

In [5]:
missing_summary = pd.DataFrame({
    "Missing_Count": raw_data.isnull().sum(),
    "Missing_Percentage": (
        raw_data.isnull().mean() * 100
    ).round(2)
})

display(missing_summary)

        Missing_Count  Missing_Percentage
Name                0                 0.0
Age                 1                25.0
City                0                 0.0
Salary              0                 0.0

In [6]:
print("Age values outside the expected demo range (0–120):")
display(raw_data[
    raw_data["Age"].notna()
    & ~raw_data["Age"].between(0, 120)
])

print("\nNegative salaries:")
display(raw_data[raw_data["Salary"] < 0])

Age values outside the expected demo range (0–120):

   Name    Age     City  Salary
3  Arun  200.0  Chennai   -5000

Negative salaries:

   Name    Age     City  Salary
3  Arun  200.0  Chennai   -5000


## 4. Data Integrity

Data integrity means maintaining the correctness and reliability
of data throughout collection, storage, transformation, and use.

Examples:
- Required fields must follow their defined rules.
- Customer IDs should be unique when required.
- Related records should reference valid IDs.
- Transformations should not unintentionally alter unrelated values.

Data integrity helps maintain trustworthy and reproducible results.


## 5. Data Leakage

Data leakage occurs when information unavailable at prediction
time influences model training or evaluation.

Examples:
- Using future information to predict a past outcome.
- Including the target variable among the input features.
- Imputing or scaling the entire dataset before splitting it.
- Using test-set information to select or tune a model.

To prevent leakage, split the data first. Fit preprocessing
transformations using training data only, then apply the fitted
transformations to validation and test data.


## 6. Training, Validation, and Test Data

**Training data:** Used to fit the machine learning model and
learn its parameters.

**Validation data:** Used to compare models, tune hyperparameters,
and make development decisions.

**Test data:** Used for final evaluation on data that was not
used for training or model selection.

A common split is 70% training, 15% validation, and 15% testing.
The appropriate split depends on dataset size, the task, and
whether the data has a time or group structure.

In [7]:
from sklearn.model_selection import train_test_split

demo = pd.DataFrame({
    "feature": range(100),
    "target": [i * 2 for i in range(100)]
})

train_data, temporary_data = train_test_split(
    demo,
    test_size=0.30,
    random_state=42
)

validation_data, test_data = train_test_split(
    temporary_data,
    test_size=0.50,
    random_state=42
)

print("Training rows:", len(train_data))
print("Validation rows:", len(validation_data))
print("Test rows:", len(test_data))

Training rows: 70
Validation rows: 15
Test rows: 15


## 7. Complete Data Preprocessing Workflow

The preprocessing workflow follows these stages:

1. Identify the dataset and understand its columns.
2. Inspect data types, missing values, duplicates, and unusual values.
3. Document the issues found during Exploratory Data Analysis.
4. Split the data into training, validation, and test sets.
5. Impute missing values using training data.
6. Encode categorical features and scale numerical features when needed.
7. Validate the transformed data.
8. Save the appropriate outputs and document the results.

The exact steps depend on the dataset and the machine learning task.

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

numerical_features = ["Age", "Salary"]
categorical_features = ["City"]

numerical_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(transformers=[
    ("numerical", numerical_pipeline, numerical_features),
    ("categorical", categorical_pipeline, categorical_features)
])

print("Preprocessing pipeline created successfully!")

Preprocessing pipeline created successfully!

In [9]:
pipeline_data = raw_data.copy()

# Remove exact duplicate rows for this demonstration.
pipeline_data = pipeline_data.drop_duplicates().copy()

# Apply a consistent category format.
pipeline_data["City"] = (
    pipeline_data["City"].str.strip().str.title()
)

# Apply the demo's documented validity rule.
pipeline_data.loc[
    ~pipeline_data["Age"].between(0, 120),
    "Age"
] = np.nan

pipeline_data.loc[
    pipeline_data["Salary"] < 0,
    "Salary"
] = np.nan

# Demonstration only: use the remaining data as a training sample.
X_demo = pipeline_data[numerical_features + categorical_features]

transformed = preprocessor.fit_transform(X_demo)

print("Original feature shape:", X_demo.shape)
print("Transformed feature shape:", transformed.shape)
print("Pipeline executed successfully!")

Original feature shape: (3, 3)
Transformed feature shape: (3, 4)
Pipeline executed successfully!

In [10]:
print("Rows after duplicate removal:", len(pipeline_data))
print("Remaining duplicate rows:", pipeline_data.duplicated().sum())

print("\nMissing values after applying demo cleaning rules:")
print(pipeline_data.isnull().sum())

print("\nFinal data types:")
print(pipeline_data.dtypes)

assert pipeline_data.duplicated().sum() == 0

print("\nValidation checks completed.")

Rows after duplicate removal: 3
Remaining duplicate rows: 0

Missing values after applying demo cleaning rules:
Name      0
Age       2
City      0
Salary    1
dtype: int64

Final data types:
Name          str
Age       float64
City          str
Salary    float64
dtype: object

Validation checks completed.


## 8. Conclusion

In this notebook, I learned the fundamentals of data preprocessing
and explored data-quality dimensions such as completeness,
consistency, accuracy, validity, and integrity.

I examined missing values, duplicate records, inconsistent
categories, and potentially invalid numerical values. I also
learned why data leakage must be prevented and how training,
validation, and test datasets are used.

Finally, I created a reusable preprocessing pipeline with numerical
imputation, categorical imputation, one-hot encoding, and scaling.

The next step is to apply these concepts to the dataset selected
during Sprint 4 and document the actual cleaning decisions.

## 9. Sprint 4 EDA Findings and Cleaning Plan

Document the actual issues identified during Sprint 4.

| Issue | Column | Planned action | Reason |
|---|---|---|---|
| Missing values | Fill in from EDA | Impute or investigate | Preserve useful records |
| Duplicate records | Fill in from EDA | Verify and remove exact duplicates | Avoid repeated observations |
| Outliers | Fill in from EDA | Investigate and handle if justified | Reduce data-quality problems |
| Inconsistent categories | Fill in from EDA | Standardize labels | Ensure consistent values |
| Incorrect data types | Fill in from EDA | Convert to correct types | Support analysis and modelling |
| Irrelevant features | Fill in from EDA | Remove only when justified | Reduce unnecessary inputs |

In [12]:
from pathlib import Path

print("Current working directory:")
print(Path.cwd())

print("\nFiles and folders available:")
for item in Path.cwd().iterdir():
    print(item.name)

Current working directory:
C:\Users\dilee

Files and folders available:
.anaconda
.aws
.azure
.cagent
.conda
.config
.continuum
.copilot
.cursor
.docker
.gemini
.git
.gitconfig
.idlerc
.ipynb_checkpoints
.ipython
.jupyter
.kube
.lesshst
.matplotlib
.minikube
.ollama
.Python_Data_Processing_Assessment.ipynb.layout
.streamlit
.vscode
.vscode-shared
01_Dataset_Understanding.ipynb
01_Data_Preprocessing_Basics.ipynb
01_NumPy_Basics.ipynb
02_Data_Inspection.ipynb
02_NumPy_Math.ipynb
03_Data_Quality.ipynb
03_NumPy_Random.ipynb
04_Pandas_Basics.ipynb
04_Univariate_Analysis.ipynb
05_Bivariate_Analysis.ipynb
05_File_Operations.ipynb
05_Probability.ipynb
06_Data_Inspection.ipynb
06_Multivariate_Analysis.ipynb
06_Probability_Distributions.ipynb
07_Data_Selection.ipynb
07_Outlier_Analysis.ipynb
07_Sampling.ipynb
08_Correlation.ipynb
08_Data_Manipulation.ipynb
08_Distribution_Analysis.ipynb
09_Categorical_Analysis.ipynb
09_GroupBy.ipynb
09_Outliers.ipynb
10_Hypothesis_Testing.ipynb
10_Merging_Data.ipynb
10_Target_Analysis.ipynb
11_Date_Time.ipynb
11_EDA_Visualization.ipynb
11_Statistical_Tests.ipynb
12_Business_Insights.ipynb
12_Feature_Relationships.ipynb
12_String_Operations.ipynb
13_EDA_Report.ipynb
13_Missing_Values.ipynb
13_Statistical_Visualization.ipynb
14_EDA_Mini_Challenge.ipynb
14_Performance_Optimization.ipynb
14_Statistics_in_ML.ipynb
15_Mini_Assess.ipynb
15_Mini_Assessment.ipynb
15_Mini_Assessments.ipynb
AppData
Application Data
application.log
banking.db
company.db
config.json
constraints_demo.db
Contacts
context_example.txt
Cookies
Data Distribution.ipynb
Documents
Downloads
employee.txt
employees.db
employees_output.csv
employees_task2.csv
Favorites
foreign_key_demo.db
hospital_project
inputs
labflow-intelligence
Links
Local Settings
logs
Measures of Central Tendency .ipynb
Measures of Dispersion.ipynb
Module_1_Python_Fundamentals.ipynb
moved_source.txt
Music
My Documents
NetHood
NTUSER.DAT
ntuser.dat.LOG1
ntuser.dat.LOG2
NTUSER.DAT{8cc2add5-0878-11f1-ba44-a083c5b06cd3}.TxR.0.regtrans-ms
NTUSER.DAT{8cc2add5-0878-11f1-ba44-a083c5b06cd3}.TxR.1.regtrans-ms
NTUSER.DAT{8cc2add5-0878-11f1-ba44-a083c5b06cd3}.TxR.2.regtrans-ms
NTUSER.DAT{8cc2add5-0878-11f1-ba44-a083c5b06cd3}.TxR.blf
NTUSER.DAT{8cc2add6-0878-11f1-ba44-a083c5b06cd3}.TM.blf
NTUSER.DAT{8cc2add6-0878-11f1-ba44-a083c5b06cd3}.TMContainer00000000000000000001.regtrans-ms
NTUSER.DAT{8cc2add6-0878-11f1-ba44-a083c5b06cd3}.TMContainer00000000000000000002.regtrans-ms
ntuser.ini
OneDrive
outputs
primary_key_demo.db
PrintHood
project_folder
Python_Data_Processing_Assessment.ipynb
Recent
relationships_demo.db
rotating_application.log
rotating_application.log.1
rotating_application.log.2
rotating_application.log.3
Saved Games
Searches
SendTo
source.txt
sprint_1_NEW
Start Menu
Statistics & Mathematics.ipynb
student.json
student.pkl
student.txt
students.csv
students.db
students.json
students.parquet
students.pkl
students.xlsx
students_1.csv
students_2.csv
student_analysis.csv
student_data.csv
Task1_Assessment
Templates
titanic_cleaned.csv
titanic_feature_engineered.csv
titanic_predictions.csv
titanic_survival_model.pkl
Untitled.ipynb
Untitled1.ipynb
Untitled2.ipynb
Untitled3.ipynb
Videos

In [13]:
from pathlib import Path

csv_files = list(Path.cwd().rglob("*.csv"))

print("CSV files found:", len(csv_files))

for file in csv_files:
    print(file)

CSV files found: 201
C:\Users\dilee\employees_output.csv
C:\Users\dilee\employees_task2.csv
C:\Users\dilee\students.csv
C:\Users\dilee\students_1.csv
C:\Users\dilee\students_2.csv
C:\Users\dilee\student_analysis.csv
C:\Users\dilee\student_data.csv
C:\Users\dilee\titanic_cleaned.csv
C:\Users\dilee\titanic_feature_engineered.csv
C:\Users\dilee\titanic_predictions.csv
C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent (1).csv
C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent (2).csv
C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent.csv
C:\Users\dilee\Downloads\House_Rent_Dataset.csv
C:\Users\dilee\Downloads\hpi_master.csv
C:\Users\dilee\inputs\employees.csv
C:\Users\dilee\outputs\employees_output.csv
C:\Users\dilee\OneDrive\Desktop\new\data\sample_events.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccosh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsin.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsinh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctan.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctanh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cbrt.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cos.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cosh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-expm1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log10.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log1p.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sin.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sinh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tan.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tanh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccosh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsin.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsinh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctan.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctanh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cbrt.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cos.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cosh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-expm1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log10.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log1p.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sin.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sinh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tan.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tanh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
C:\Users\dilee\Downloads\spark-4.1.1-bin-hadoop3\spark-4.1.1-bin-hadoop3\python\test_support\sql\ages_newlines.csv
C:\Users\dilee\Downloads\spark-4.1.1-bin-hadoop3\spark-4.1.1-bin-hadoop3\examples\src\main\resources\people.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\admin_owner_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\customer_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\._admin_owner_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\._customer_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\data\._chennai_real_estate_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\tornado\test\csv_translations\._fr_FR.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._mt19937-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._mt19937-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64dxsm-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64dxsm-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._philox-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._philox-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._sfc64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._sfc64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arccos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arccosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arcsin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arcsinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arctan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arctanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-cbrt.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-cos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-cosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-exp.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-exp2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-expm1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log10.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log1p.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-sin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-sinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-tan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-tanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\matplotlib\mpl-data\sample_data\._data_x_x2_x3.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\matplotlib\mpl-data\sample_data\._msft.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\matplotlib\mpl-data\sample_data\._Stocks.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\data\chennai_real_estate_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\tornado\test\csv_translations\fr_FR.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arccos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arccosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arcsin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arcsinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arctan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arctanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-cbrt.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-cos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-cosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-exp.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-exp2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-expm1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log10.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log1p.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-sin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-sinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-tan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-tanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\matplotlib\mpl-data\sample_data\data_x_x2_x3.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\matplotlib\mpl-data\sample_data\msft.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\matplotlib\mpl-data\sample_data\Stocks.csv
C:\Users\dilee\AppData\Local\seaborn\seaborn\Cache\tips.csv
C:\Users\dilee\AppData\Local\seaborn\seaborn\Cache\titanic.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\test\csv_translations\fr_FR.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\breast_cancer.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\iris.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\linnerud_exercise.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\linnerud_physiological.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\wine_data.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv

In [15]:
from pathlib import Path
import pandas as pd

print("Current folder:", Path.cwd())
print("Path exists:", Path("data").exists())

if Path("data").exists():
    print("Files inside data folder:")
    for file in Path("data").iterdir():
        print(file.name)

Current folder: C:\Users\dilee
Path exists: False

In [16]:
from pathlib import Path

for file in Path.cwd().rglob("*.csv"):
    print(file)

C:\Users\dilee\employees_output.csv
C:\Users\dilee\employees_task2.csv
C:\Users\dilee\students.csv
C:\Users\dilee\students_1.csv
C:\Users\dilee\students_2.csv
C:\Users\dilee\student_analysis.csv
C:\Users\dilee\student_data.csv
C:\Users\dilee\titanic_cleaned.csv
C:\Users\dilee\titanic_feature_engineered.csv
C:\Users\dilee\titanic_predictions.csv
C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent (1).csv
C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent (2).csv
C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent.csv
C:\Users\dilee\Downloads\House_Rent_Dataset.csv
C:\Users\dilee\Downloads\hpi_master.csv
C:\Users\dilee\inputs\employees.csv
C:\Users\dilee\outputs\employees_output.csv
C:\Users\dilee\OneDrive\Desktop\new\data\sample_events.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccosh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsin.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsinh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctan.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctanh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cbrt.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cos.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cosh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-expm1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log10.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log1p.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sin.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sinh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tan.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tanh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccosh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsin.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsinh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctan.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctanh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cbrt.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cos.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cosh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-expm1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log10.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log1p.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sin.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sinh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tan.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tanh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
C:\Users\dilee\Downloads\spark-4.1.1-bin-hadoop3\spark-4.1.1-bin-hadoop3\python\test_support\sql\ages_newlines.csv
C:\Users\dilee\Downloads\spark-4.1.1-bin-hadoop3\spark-4.1.1-bin-hadoop3\examples\src\main\resources\people.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\admin_owner_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\customer_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\._admin_owner_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\._customer_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\data\._chennai_real_estate_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\tornado\test\csv_translations\._fr_FR.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._mt19937-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._mt19937-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64dxsm-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64dxsm-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._philox-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._philox-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._sfc64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._sfc64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arccos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arccosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arcsin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arcsinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arctan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arctanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-cbrt.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-cos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-cosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-exp.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-exp2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-expm1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log10.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log1p.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-sin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-sinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-tan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-tanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\matplotlib\mpl-data\sample_data\._data_x_x2_x3.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\matplotlib\mpl-data\sample_data\._msft.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\matplotlib\mpl-data\sample_data\._Stocks.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\data\chennai_real_estate_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\tornado\test\csv_translations\fr_FR.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arccos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arccosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arcsin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arcsinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arctan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arctanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-cbrt.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-cos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-cosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-exp.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-exp2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-expm1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log10.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log1p.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-sin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-sinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-tan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-tanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\matplotlib\mpl-data\sample_data\data_x_x2_x3.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\matplotlib\mpl-data\sample_data\msft.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\matplotlib\mpl-data\sample_data\Stocks.csv
C:\Users\dilee\AppData\Local\seaborn\seaborn\Cache\tips.csv
C:\Users\dilee\AppData\Local\seaborn\seaborn\Cache\titanic.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\test\csv_translations\fr_FR.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\breast_cancer.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\iris.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\linnerud_exercise.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\linnerud_physiological.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\wine_data.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccosh.csv

In [18]:
from pathlib import Path

print("Current notebook folder:", Path.cwd())

print("\nCSV files found:")
for file in Path.cwd().rglob("*.csv"):
    print(file)

Current notebook folder: C:\Users\dilee

CSV files found:
C:\Users\dilee\employees_output.csv
C:\Users\dilee\employees_task2.csv
C:\Users\dilee\students.csv
C:\Users\dilee\students_1.csv
C:\Users\dilee\students_2.csv
C:\Users\dilee\student_analysis.csv
C:\Users\dilee\student_data.csv
C:\Users\dilee\titanic_cleaned.csv
C:\Users\dilee\titanic_feature_engineered.csv
C:\Users\dilee\titanic_predictions.csv
C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent (1).csv
C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent (2).csv
C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent.csv
C:\Users\dilee\Downloads\House_Rent_Dataset.csv
C:\Users\dilee\Downloads\hpi_master.csv
C:\Users\dilee\inputs\employees.csv
C:\Users\dilee\outputs\employees_output.csv
C:\Users\dilee\OneDrive\Desktop\new\data\sample_events.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccosh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsin.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsinh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctan.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctanh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cbrt.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cos.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cosh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-expm1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log10.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log1p.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sin.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sinh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tan.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tanh.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
C:\Users\dilee\OneDrive\Desktop\new\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccosh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsin.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsinh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctan.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctanh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cbrt.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cos.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cosh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-expm1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log10.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log1p.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sin.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sinh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tan.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tanh.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
C:\Users\dilee\labflow-intelligence\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
C:\Users\dilee\Downloads\spark-4.1.1-bin-hadoop3\spark-4.1.1-bin-hadoop3\python\test_support\sql\ages_newlines.csv
C:\Users\dilee\Downloads\spark-4.1.1-bin-hadoop3\spark-4.1.1-bin-hadoop3\examples\src\main\resources\people.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\admin_owner_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\customer_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\._admin_owner_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\._customer_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\data\._chennai_real_estate_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\tornado\test\csv_translations\._fr_FR.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._mt19937-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._mt19937-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64dxsm-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._pcg64dxsm-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._philox-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._philox-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._sfc64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\random\tests\data\._sfc64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arccos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arccosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arcsin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arcsinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arctan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-arctanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-cbrt.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-cos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-cosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-exp.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-exp2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-expm1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log10.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log1p.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-log2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-sin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-sinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-tan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\numpy\core\tests\data\._umath-validation-set-tanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\matplotlib\mpl-data\sample_data\._data_x_x2_x3.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\matplotlib\mpl-data\sample_data\._msft.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\__MACOSX\langchain-ask-csv-main\myenv311\lib\python3.11\site-packages\matplotlib\mpl-data\sample_data\._Stocks.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\data\chennai_real_estate_data.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\tornado\test\csv_translations\fr_FR.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arccos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arccosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arcsin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arcsinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arctan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-arctanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-cbrt.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-cos.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-cosh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-exp.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-exp2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-expm1.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log10.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log1p.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-log2.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-sin.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-sinh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-tan.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\numpy\core\tests\data\umath-validation-set-tanh.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\matplotlib\mpl-data\sample_data\data_x_x2_x3.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\matplotlib\mpl-data\sample_data\msft.csv
C:\Users\dilee\Downloads\langchain-ask-csv-main\langchain-ask-csv-main\venv\Lib\site-packages\matplotlib\mpl-data\sample_data\Stocks.csv
C:\Users\dilee\AppData\Local\seaborn\seaborn\Cache\tips.csv
C:\Users\dilee\AppData\Local\seaborn\seaborn\Cache\titanic.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\test\csv_translations\fr_FR.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\breast_cancer.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\iris.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\linnerud_exercise.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\linnerud_physiological.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\data\wine_data.csv
C:\Users\dilee\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv

In [19]:
from pathlib import Path

downloads = Path.home() / "Downloads"

print("Downloads folder:", downloads)
print("Folder exists:", downloads.exists())

if downloads.exists():
    for file in downloads.glob("*.csv"):
        print(file.name)

Downloads folder: C:\Users\dilee\Downloads
Folder exists: True
chennai_real_estate_100k_structured_40percent (1).csv
chennai_real_estate_100k_structured_40percent (2).csv
chennai_real_estate_100k_structured_40percent.csv
House_Rent_Dataset.csv
hpi_master.csv

In [21]:
from pathlib import Path
import pandas as pd

downloads = Path.home() / "Downloads"

print("Home folder:", Path.home())
print("Downloads folder exists:", downloads.exists())

print("\nCSV files in Downloads:")
if downloads.exists():
    files = list(downloads.glob("*.csv"))
    if files:
        for file in files:
            print(file.name)
    else:
        print("No CSV files found in Downloads.")

Home folder: C:\Users\dilee
Downloads folder exists: True

CSV files in Downloads:
chennai_real_estate_100k_structured_40percent (1).csv
chennai_real_estate_100k_structured_40percent (2).csv
chennai_real_estate_100k_structured_40percent.csv
House_Rent_Dataset.csv
hpi_master.csv

In [23]:
from pathlib import Path
import pandas as pd

print("Python home directory:", Path.home())
print("Current notebook directory:", Path.cwd())

print("\nSearching for CSV files...")

search_locations = [
    Path.cwd(),
    Path.home() / "Downloads",
    Path.home() / "Desktop",
]

for folder in search_locations:
    if folder.exists():
        print(f"\nChecking: {folder}")
        for file in folder.glob("*.csv"):
            print("Found:", file)

Python home directory: C:\Users\dilee
Current notebook directory: C:\Users\dilee

Searching for CSV files...

Checking: C:\Users\dilee
Found: C:\Users\dilee\employees_output.csv
Found: C:\Users\dilee\employees_task2.csv
Found: C:\Users\dilee\students.csv
Found: C:\Users\dilee\students_1.csv
Found: C:\Users\dilee\students_2.csv
Found: C:\Users\dilee\student_analysis.csv
Found: C:\Users\dilee\student_data.csv
Found: C:\Users\dilee\titanic_cleaned.csv
Found: C:\Users\dilee\titanic_feature_engineered.csv
Found: C:\Users\dilee\titanic_predictions.csv

Checking: C:\Users\dilee\Downloads
Found: C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent (1).csv
Found: C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent (2).csv
Found: C:\Users\dilee\Downloads\chennai_real_estate_100k_structured_40percent.csv
Found: C:\Users\dilee\Downloads\House_Rent_Dataset.csv
Found: C:\Users\dilee\Downloads\hpi_master.csv

In [25]:
if "df" in globals():
    print("Dataset is loaded!")
    print("Dataset shape:", df.shape)
    display(df.head())
else:
    print("Dataset is not loaded yet. Load your CSV before continuing.")

Dataset is not loaded yet. Load your CSV before continuing.

In [26]:
print("Dataset Information:")
df.info()

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Shape:")
print(df.shape)

Dataset Information:

NameError: name 'df' is not defined

In [27]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
display(missing_values[missing_values > 0].sort_values(ascending=False))

print("\nTotal missing values:", df.isnull().sum().sum())

NameError: name 'df' is not defined

In [28]:
print("Total duplicate rows:", df.duplicated().sum())

NameError: name 'df' is not defined

In [29]:
display(df.describe())

NameError: name 'df' is not defined

In [30]:
# Calculate missing values
missing_count = df.isnull().sum()

# Calculate missing percentage
missing_percentage = (df.isnull().mean() * 100).round(2)

# Create a summary table
missing_summary = pd.DataFrame({
    "Missing_Count": missing_count,
    "Missing_Percentage": missing_percentage
})

# Show columns containing missing values
missing_summary = missing_summary[
    missing_summary["Missing_Count"] > 0
].sort_values(by="Missing_Percentage", ascending=False)

display(missing_summary)

NameError: name 'df' is not defined

In [31]:
import matplotlib.pyplot as plt

missing_count = df.isnull().sum()
missing_count = missing_count[missing_count > 0]

if len(missing_count) > 0:
    missing_count.plot(kind="bar", figsize=(10, 5))
    plt.title("Missing Values by Column")
    plt.xlabel("Columns")
    plt.ylabel("Number of Missing Values")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()
else:
    print("No missing values found in the dataset.")

NameError: name 'df' is not defined